common: use glue block

diff --git a/bin/silent_run b/bin/silent_run
--- a/bin/silent_run
+++ b/bin/silent_run
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# BEGIN: corpusops common glue
 # scripts vars
 SCRIPT=$0
 LOGGER_NAME=${LOGGER_NAME-$(basename $0)}
@@ -8,6 +9,23 @@ SCRIPT_DIR=$(cd "$(dirname $0)" && pwd)
 OW="${OW:-$(pwd)}"
 # W is script_dir/..
 W=${W:-$(cd "$SCRIPT_DIR/.." && pwd)}
+#
+#
+DEFAULTS_COPS_ROOT="/srv/corpusops/corpusops.bootstrap"
+DEFAULTS_COPS_URL="https://github.com/corpusops/corpusops.bootstrap"
+
+COPS_ROOT=${COPS_ROOT-$DEFAULTS_COPS_ROOT}
+COPS_URL=${COPS_URL-$DEFAULTS_COPS_URL}
+BASE_PREPROVISION_IMAGES="ubuntu:latest_preprovision"
+BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:16.04_preprovision"
+BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:14.04_preprovision"
+BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/centos:7_preprovision"
+BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:latest"
+BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:16.04"
+BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:14.04"
+BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/centos:7"
+BASE_IMAGES="$BASE_PREPROVISION_IMAGES $BASE_CORE_IMAGES"
+#
 # colors
 RED="\\e[0;31m"
 CYAN="\\e[0;36m"
@@ -34,6 +52,9 @@ parse_cli_common() {
     if [[ -n ${USAGE} ]]; then
         usage
     fi
+}
+is_ci() {
+    return $( ( [[ -n ${TRAVIS-} ]] || [[ -n ${GITLAB_CI} ]] );echo $?;)
 }
 log_() {
     reset_colors;msg_color=${2:-${YELLOW}};
@@ -96,7 +117,7 @@ output_in_error() { ( do_trap output_in_error_post EXIT TERM QUIT INT;\
                       output_in_error_ "${@}" ; ); }
 output_in_error_(){
     if [[ -n ${OUTPUT_IN_ERROR_DEBUG-} ]];then set -x;fi
-    if [[ -n $TRAVIS ]] || [[ -n $GITLAB_CI ]];then
+    if is_ci;then
         DEFAULT_CI_BUILD=y
     fi
     CI_BUILD="${CI_BUILD-${DEFAULT_CI_BUILD-}}"
@@ -160,13 +181,276 @@ output_in_error_post() {
 }
 test_silent_log() { ( [[ -z ${NO_SILENT-} ]] && ( [[ -n ${SILENT_LOG-} ]] || [[ -n "${SILENT_DEBUG}" ]] ) ); }
 test_silent() { ( [[ -z ${NO_SILENT-} ]] && ( [[ -n ${SILENT-} ]] || test_silent_log ) ); }
-silent_run_() { (LOG=${SILENT_LOG:-${LOG}};NO_OUTPUT=;\
-                 if test_silent;then NO_OUTPUT=y;fi;output_in_error "$@";) }
+silent_run_() {
+    (LOG=${SILENT_LOG:-${LOG}};NO_OUTPUT=${NO_OUTPUT-};\
+     if test_silent;then NO_OUTPUT=y;fi;output_in_error "$@";)
+}
 silent_run() { ( silent_run_ "${@}" ; ); }
 run_silent() { SILENT=${SILENT-1} silent_run "${@}"; }
 vvv() { debug "${@}";silent_run "${@}"; }
 vv() { log "${@}";silent_run "${@}";}
 silent_vv() { SILENT_LOG=${SILENT_LOG-} SILENT=${SILENT-1} vv "${@}"; }
+version_lte() { [  "$1" = "$(printf "$1\n$2" | sort -V | head -n1)" ]; }
+version_lt() { [ "$1" = "$2" ] && return 1 || version_lte $1 $2; }
+version_gte() { [  "$2" = "$(printf "$1\n$2" | sort -V | head -n1)" ]; }
+version_gt() { [ "$1" = "$2" ] && return 1 || version_gte $1 $2; }
+is_archlinux_like() { echo $DISTRIB_ID | egrep -iq "archlinux"; }
+is_debian_like() { echo $DISTRIB_ID | egrep -iq "debian|ubuntu|mint"; }
+is_redhat_like() { echo $DISTRIB_ID | egrep -iq "fedora|centos|redhat|red-hat"; }
+set_lang() { locale=${1:-C};export LANG=${locale};export LC_ALL=${locale}; }
+detect_os() {
+    # this function should be copiable in other scripts, dont use adjacent functions
+    UNAME="${UNAME:-"$(uname | awk '{print tolower($1)}')"}"
+    PATH="${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
+    SED="sed"
+    if [ "x${UNAME}" != "xlinux" ] && hash -r gsed >/dev/null 2>&1; then
+        SED=gsed
+    fi
+    DISTRIB_CODENAME=""
+    DISTRIB_ID=""
+    DISTRIB_RELEASE=""
+    if hash -r lsb_release >/dev/null 2>&1; then
+        DISTRIB_ID=$(lsb_release -si)
+        DISTRIB_CODENAME=$(lsb_release -sc)
+        DISTRIB_RELEASE=$(lsb_release -sr)
+    elif [ -e /etc/lsb-release ];then
+        debug "No lsb_release, sourcing manually /etc/lsb-release"
+        DISTRIB_ID=$(. /etc/lsb-release;echo ${DISTRIB_ID})
+        DISTRIB_CODENAME=$(. /etc/lsb-release;echo ${DISTRIB_CODENAME})
+        DISTRIB_RELEASE=$(. /etc/lsb-release;echo ${DISTRIB_RELEASE})
+    elif [ -e /etc/os-release ];then
+        DISTRIB_ID=$(. /etc/os-release;echo $ID)
+        DISTRIB_CODENAME=$(. /etc/os-release;echo $VERSION)
+        DISTRIB_CODENAME=$(echo $DISTRIB_CODENAME |sed -e "s/.*(\([^)]\+\))/\1/")
+        DISTRIB_RELEASE=$(. /etc/os-release;echo $VERSION_ID)
+    elif [ -e /etc/redhat-release ];then
+        RHRELEASE=$(cat /etc/redhat-release)
+        DISTRIB_CODENAME=${RHRELEASE}
+        DISTRIB_RELEASE=${RHRELEASE}
+        DISTRIB_ID=${RHRELEASE}
+        DISTRIB_CODENAME=$(echo $DISTRIB_CODENAME |sed -e "s/.*(\([^)]\+\))/\1/")
+        DISTRIB_RELEASE=$(echo $DISTRIB_RELEASE |sed -e "s/release \([0-9]\)/\1/")
+        DISTRIB_ID=$(echo $DISTRIB_ID | awk '{print tolower($1)}')
+    else
+        if ! ( echo ${@-} | grep -q no_fail );then
+            echo "unexpected case, no lsb_release" >&2
+            exit 1
+        fi
+    fi
+    export DISTRIB_ID DISTRIB_CODENAME DISTRIB_RELEASE
+}
+get_command() {
+    local p=
+    local cmd="${@}"
+    if which which >/dev/null 2>/dev/null;then
+        p=$(which "${cmd}" 2>/dev/null)
+    fi
+    if [ "x${p}" = "x" ];then
+        p=$(export IFS=:;
+            echo "${PATH-}" | while read -ra pathea;do
+                for pathe in "${pathea[@]}";do
+                    pc="${pathe}/${cmd}";
+                    if [ -x "${pc}" ]; then
+                        p="${pc}"
+                    fi
+                done
+                if [ "x${p}" != "x" ]; then echo "${p}";break;fi
+            done )
+    fi
+    if [ "x${p}" != "x" ];then
+        echo "${p}"
+    fi
+}
+cleanup_docker_tag() { echo "${@}"|sed -re "s/\.|[-_]//g"|awk '{print tolower($0)}'; }
+get_container_id() { local n=${1};local cid=$(docker ps -q -a --filter 'name='$n); echo "${cid}"; }
+sane_container_name() { local n=${1};n=${n//:/};n=${n//_/};n=${n//-/};n=${n//\//};n=${n//\./};echo $n; }
+get_images() { docker images --no-trunc -q "${@}" 2>/dev/null|awk '!seen[$0]++'; }
+get_image() { get_images "${@}" | head -n 1; }
+get_docker_ids() { docker inspect -f '{{.Id}}' "${@}" 2>/dev/null; }
+save_container() {
+    local n="${1}"
+    local d="${2:-${n}}"
+    local running=$(docker ps -q    --filter 'name='$n)
+    if [[ -n "${running}" ]];then
+        vv docker kill "${running}"
+    fi
+    local cid=$(get_container_id $n)
+    if [[ -n "${cid}" ]];then
+        vv docker commit "$cid" "$d"
+        vv docker rm "$cid"
+    else
+        img=${initial_img}
+    fi
+}
+get_git_changeset() { ( cd "${1:-$(pwd)}" && git log HEAD|head -n1|awk '{print $2}'); }
+get_git_branch() {
+   ( cd "${1:-$(pwd)}" &&\
+     git rev-parse --abbrev-ref HEAD | grep -v HEAD || \
+     git describe --exact-match HEAD 2> /dev/null || \
+     git rev-parse HEAD)
+}
+get_git_branchs() { ( cd "${1:-$(pwd)}" && git branch|sed -e "s/^\*\? \+//g"); }
+get_full_chrono() { date "+%F_%H-%M-%S-%N"; }
+get_random_slug() { len=${1:-32};strings=${2:-'a-zA-Z0-9'};echo "$(cat /dev/urandom|tr -dc "$strings"|fold -w ${len}|head -n 1)"; }
+may_sudo() {
+    if [ "$(whoami)" != "root" ] && [ -z "${NO_SUDO-}" ];then
+        echo "sudo $([[ -z $DIRECT_SUDO ]] && echo "-HE")"
+    fi
+}
+get_ancestor_from_dockerfile() {
+    local dockerfile=${1}
+    local ancestor=
+    if [[ -e "${dockerfile}" ]] && egrep -q ^FROM "${dockerfile}"; then
+        ancestor=$(egrep ^FROM "${dockerfile}"\
+            | head -n1 | awk '{print $2}' | xargs -n1| sort -u )
+    fi
+    echo ${ancestor}
+}
+do_tmp_cleanup() {
+    local tmp_dockers=$2
+    local tmp_files=$1
+    local tmp_imgs=$3
+    log "Post cleanup"
+    for tmp_file in ${tmp_files};do
+        if [ -e "${tmp_file}" ]; then
+            vv rm -f "${tmp_file}"
+        fi
+    done
+    for test_docker in ${tmp_dockers};do
+        test_dockerid=$(vvv get_container_id ${test_docker})
+        if [[ "${test_dockerid}" != "" ]]; then
+            log "Removing produced test docker ${test_docker}"
+            docker rm -f "${test_dockerid}"
+        fi
+    done
+    for test_tag in ${tmp_imgs};do
+        test_tagid=$(vvv get_image ${test_tag})
+        if [[ "${test_tagid}" != "" ]]; then
+            log "Removing produced test image: ${test_tag}"
+            docker rmi "${test_tagid}"
+        fi
+    done
+}
+update_wd_to_br() {
+    (
+        local wd="${2:-$(pwd)}"
+        local up_branch="${1}"
+        cd "${wd}" || die "${wd} does not exists"
+        if ! git diff --exit-code -q;then
+            git stash
+        fi &&\
+        vv git pull origin "${up_branch}"
+    )
+
+}
+upgrade_wd_to_br() {
+    (
+        local wd="${2:-$(pwd)}"
+        local up_branch="${1}"
+        cd "${wd}" || die "${wd} does not exists"
+        local test_branch="${3:-$(get_git_branch)}"
+        local existing_gitmodules="$(git submodule status|awk '{print $2}')"
+        if [ "x${test_branch}" != "x${up_branch}" ];then
+            warn "Upgrading $wd to branch: $up_branch"
+            git fetch --all || die "git fetch in $wd failed"
+            if get_git_branchs | egrep -q "^${up_branch}$";then
+                vv git checkout ${up_branch} &&\
+                    vv git reset --hard origin/${up_branch}
+            else
+                vv git checkout origin/${up_branch} -b ${up_branch}
+            fi
+        fi
+        update_wd_to_br $(get_ansible_branch) "${VENV_PATH}/src/ansible" &&\
+        while read subdir;do
+            subdir=$(echo $subdir|sed -e "s/^\.\///g")
+            if [ -h "${subdir}/.git" ] || [ -f "${subdir}/.git" ];then
+                debug "Checking if ${subdir} is always a submodule"
+                if [ -e .gitmodules ] && ( grep -q -- "${subdir}" .gitmodules );then
+                    debug "${subdir} is always a gitmodule"
+                else
+                    warn "${subdir} is not a git submodule anymore"
+                    vv rm -rf "${subdir}"
+                fi
+            fi
+        done < <( echo "${existing_gitmodules}" )
+        if [ -e .gitmodules ];then
+            warn "Upgrading submodules in $wd"
+            vv git submodule update --recursive
+        fi
+    )
+}
+get_python2_() {
+    local py2=
+    for i in python2.7 python2.6 python-2.7 python-2.6 python-2;do
+        local lpy=$(get_command $i 2>/dev/null)
+        if [[ -n $lpy ]] && ( ${lpy} -V 2>&1| egrep -qi 'python 2' );then
+            py2=${lpy}
+            break
+        fi
+    done
+    echo $py2
+}
+get_python2() { ( deactivate 2>/dev/null;get_python2_; ) }
+make_virtualenv() {
+    local py=${1:-$(get_python2)}
+    local DEFAULT_VENV_PATH=$(pwd)/venv
+    local venv_path=${2-${VENV_PATH:-$DEFAULT_VENV_PATH}}
+    local PIP_CACHE=${PIP_CACHE:-${venv_path}/cache}
+    if [ "x${DEFAULT_VENV_PATH}" != "${venv_path}" ];then
+        if [ ! -e "${venv_path}" ];then
+            mkdir -p "${venv_path}"
+        fi
+        if [ -e "${DEFAULT_VENV_PATH}" ] && \
+            [ "$DEFAULT_VENV_PATH" != "$venv_path" ] &&\
+            [ ! -h "${DEFAULT_VENV_PATH}" ];then
+            die "$DEFAULT_VENV_PATH is not a symlink but we want to create it"
+        fi
+        if [ -h $DEFAULT_VENV_PATH ] &&\
+            [ "x$(readlink $DEFAULT_VENV_PATH)" != "$venv_path" ];then
+            rm -f "${DEFAULT_VENV_PATH}"
+        fi
+        if [ ! -e $DEFAULT_VENV_PATH ];then
+            ln -s "${venv_path}" "${DEFAULT_VENV_PATH}"
+        fi
+    fi
+    if     [ ! -e "${venv_path}/bin/activate" ] \
+        || [ ! -e "${venv_path}/lib" ] \
+        || [ ! -e "${venv_path}/include" ] \
+        ; then
+        bs_log "Creating virtualenv in ${venv_path}"
+        if [ ! -e "${PIP_CACHE}" ]; then
+            mkdir -p "${PIP_CACHE}"
+        fi
+        if [ ! -e "${venv_path}" ]; then
+            mkdir -p "${venv_path}"
+        fi
+    virtualenv \
+        $( [[ -n $py ]] && echo "--python=$py"; ) \
+        --system-site-packages --unzip-setuptools \
+        "${venv_path}" &&\
+    ( . "${venv_path}/bin/activate" &&\
+      "${venv_path}/bin/easy_install" -U setuptools &&\
+      "${venv_path}/bin/pip" install -U pip &&\
+      deactivate; )
+    fi
+}
+ensure_last_python_requirement() {
+    local i=
+    local copt=
+    local PIP_CACHE=${PIP_CACHE:-${VENV_PATH}/cache}
+    if pip --help | grep -q download-cache; then
+        copt="--download-cache"
+    else
+        copt="--cache-dir"
+    fi
+    for i in $@;do
+        log "Installing last version of $i"
+        pip install -U $copt "${PIP_CACHE}" $i
+    done
+}
+usage() { die 128 "No usage found"; }
+# END: corpusops common glue
+
 usage() {
     NO_HEADER=y die '
 Wrapper to call a command than can
