hacking: finish  role travis

diff --git a/hacking/travis.role.yml b/hacking/travis.role.yml
--- a/hacking/travis.role.yml
+++ b/hacking/travis.role.yml
@@ -10,22 +10,43 @@ language: python
 python: "2.7"
 before_install:
   - sudo apt-get update -qq
-  - >
-    set -ex;
-    for i in $IMAGES;do
-     img="corpusops/$i";
-     n="${img//:/}";
-     n="${img//\\./}";
-     docker pull "$img";
-     docker run --name="$n" "cops${img}" "$img" /bin/true;
-     docker cp "$n":/srv/corpusops "/srv/corpusops.${i}";
-    done
 install:
-script:
-  - > 
-    set -ex;
-    for i in $IMAGES;do
-      if [ -e /srv/corpusops ];then rm -fv /srv/corpusops;fi;
-      ln -sf "/srv/corpusops.${i}" "/srv/corpusops";
-      "/srv/corpusops/hacking/test_roles" "$PWD";
+  - |
+    set -e;
+    for i in $(echo "$IMAGES ubuntu:14.04"|xargs -n1|sort -u);do
+     img="corpusops/$i"
+     echo "docker pull $img"
+     sudo docker pull "$img"
     done
+  - |
+    cat > copstest_test.sh << TEOF
+    #!/usr/bin/env bash
+    cd /srv/corpusops/corpusops.bootstrap
+    if ! hacking/test_roles "$PWD";then
+      echo "First test try failed, try to update code and retry test" >&2
+      bin/install.sh -s
+      hacking/test_roles "$PWD"
+    fi
+    TEOF
+    #
+  - cat copstest_test.sh
+  - chmod +x copstest_*.sh
+  - |
+    set -e;
+    docker=$(which docker)
+    sudo docker run -d --name=copstestrunner \
+       $( while read v; do echo " -v ${v}:${v}:ro";done < \
+               <( ldd "${docker}"|awk '{print $3}'|egrep '^/'; )
+       )\
+       -v "${docker}:${docker}" \
+       -v "/sys/fs/cgroup:/sys/fs/cgroup:ro" \
+       -v "/var/lib/docker:/var/lib/docker" \
+       -v "/var/run/docker:/var/run/docker" \
+       -v "/var/run/docker.sock:/var/run/docker.sock" \
+       -v "/:/HOST_ROOTFS" \
+       -v "$PWD:$PWD" \
+       -e IMAGES="$IMAGES" \
+       "corpusops/ubuntu:14.04" bash -c 'while true;do sleep 65200;done'
+script:
+  - sudo docker exec copstestrunner bash -c "$PWD/copstest_test.sh"
+
