Install also  dockerize

diff --git a/docker/corpusops/debian:stretch_preprovision b/docker/corpusops/debian:stretch_preprovision
--- a/docker/corpusops/debian:stretch_preprovision
+++ b/docker/corpusops/debian:stretch_preprovision
@@ -68,9 +68,8 @@ RUN bash -c '\
     && for k in $GPG_KEYS;do \
         touch /k_$k \
         && for s in $GPG_KEYS_SERVERS;do \
-          echo "Keyserver try :$s" >&2 && \
           if ( gpg -q --batch --keyserver $s --recv-keys $k );then \
-            rm -f /k_$k && break;fi;done \
+            rm -f /k_$k && break;else echo "Keyserver failed: $s" >&2;fi;done \
         && if [ -e /k_$k ];then exit 1;fi \
        done \
     && urls="$( curl -s "https://api.github.com/repos/tianon/gosu/releases/latest" \
